# spring.application.name=config

spring:
  application:
    name: config

my:
  key1: hello
  key2: 100

person:
  id: 1
  name: huanhuan
  age: 30

dbtypes:
  name:
    - mysql
    - huanhuan
    - love
  map:
    k1: kk1
    k2: kk2
    k3: kk3

