spring:
  application:
    name: langchain4j-spring
langchain4j:
  community:
    dashscope:
      streaming-chat-model:
        api-key: sk-defa3605b5a347c68c684dc2ae4d1263
        model-name: qwen-plus
