@startuml
actor 我
participant 宿舍
participant 教室
participant 食堂

==上午==
我 -> 宿舍: 7:30 起床，洗漱
我 -> 食堂: 8:00 吃饭
我 -> 教室: 8:30-9:15 上课
教室 -> 我: 9:15-9:35 大课间休息
我 -> 教室: 9:35-10:20 上课）
教室 -> 我: 10:20-10:40 大课间休息
我 -> 教室: 10:40-11:25 上课
教室 -> 我: 11:25-11:45 大课间休息
我 -> 教室: 11:45-12:30 上课
我 -> 宿舍: 12:30 回宿舍睡觉

== 中午 ==
我 -> 食堂: 12:00 吃饭
我 -> 宿舍: 12:30 睡觉

== 下午 ==
我 -> 教室: 14:00-14:45 上课
教室 -> 我: 14:45-15:05 大课间休息，买瓶饮料
我 -> 教室: 15:05-15:50 上课
教室 -> 我: 15:50-16:10 大课间休息，和同学聊考试
我 -> 教室: 16:10-16:55 上课
教室 -> 我: 16:55-17:15 大课间休息，伸展身体
我 -> 教室: 17:15-17:30 上课
我 -> 食堂: 17:40 吃晚饭，吃杂酱面

== 晚上 ==
我 -> 教室: 19:00-19:45 上课
教室 -> 我: 19:45-20:05 大课间休息
我 -> 教室: 20:05-20:50 上课
我 -> 宿舍: 21:00 回宿舍，洗漱
我 -> 宿舍: 21:30 吃屎
我 -> 宿舍: 22:30 上床睡觉
@enduml